public class Address {
    public void homeAddress() {
        //1
        string name = 'Mary';
        System.debug('Your Name:' + name);
        //2
        integer numberOfMember = 4;
        System.debug('Total number of members in your family: ' + numberOfMember);
        
        //3
        string houseName = 'happyHouse';
        System.debug('House Name: ' +houseName);
        
        //4
        String houseNumber = '123';
        System.debug('House Number: ' + houseNumber);
        
        //5
        string streetName = 'Batchelder';
        System.debug('Street Name: ' + streetName);

        //6
        string cityName = 'Dallas';
        System.debug('City Name: ' + cityName);

        //7
        string stateName = 'Texas';
        System.debug('State Name: ' + stateName);

        //8
        string stateIsoCode = '3166-2:US';
        System.debug('State ISO Code: ' + stateIsoCode);

        //9
        string countryName = 'UNITED STATE';
        System.debug('Country Name: ' + countryName);

        //10
        string countryIsoCode ='USA';
        System.debug('Country ISO Code: ' + countryIsoCode);

        //11
        string zipCode = '11235';
        System.debug('Zip Code: ' + zipCode);

        //12
        boolean isMyHome = true;
        System.debug('Is this your current home or not: ' + isMyHome);

    }
}
